// export const surpriseMePrompts = [
//     'an armchair in the shape of an avocado',
//     'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
//     'teddy bears shopping for groceries in Japan, ukiyo-e',
//     'an oil painting by Matisse of a humanoid robot playing chess',
//     'panda mad scientist mixing sparkling chemicals, digital art',
//     "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
//     '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
//     'an astronaut lounging in a tropical resort in space, vaporwave',
//     'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
//     'a stained glass window depicting a hamburger and french fries',
//     'a pencil and watercolor drawing of a bright city in the future with flying cars',
//     'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
//     'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
//     '"a sea otter with a pearl earring" by Johannes Vermeer',
//     'an oil pastel drawing of an annoyed cat in a spaceship',
//     'a painting of a fox in the style of Starry Night',
//     'a bowl of soup that looks like a monster, knitted out of wool',
//     'A plush toy robot sitting against a yellow wall',
//     'A synthwave style sunset above the reflecting water of the sea, digital art',
//     'Two futuristic towers with a skybridge covered in lush foliage, digital art',
//     'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
//     'A comic book cover of a superhero wearing headphones',
//     'A centered explosion of colorful powder on a black background',
//     'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
//     'A photo of a white fur monster standing in a purple room',
//     "A photo of Michelangelo's sculpture of David wearing headphones djing",
//     'A Samurai riding a Horse on Mars, lomography.',
//     'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
//     'A realistic photograph of a young woman with blue eyes and blonde hair',
//     'A man standing in front of a stargate to another dimension',
//     'Spongebob Squarepants in the Blair Witch Project',
//     'A velociraptor working at a hotdog stand, lomography',
//     'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
//     'A BBQ that is alive, in the style of a Pixar animated movie',
//     'A futuristic cyborg dance club, neon lights',
//     'The long-lost Star Wars 1990 Japanese Anime',
//     'A hamburger in the shape of a Rubik’s cube, professional food photography',
//     'A Synthwave Hedgehog, Blade Runner Cyberpunk',
//     'An astronaut encountering an alien life form on a distant planet, photography',
//     'A Dinosaur exploring Cape Town, photography',
//     'A Man falling in Love with his Computer, digital art',
//     'A photograph of a cyborg exploring Tokyo at night, lomography',
//     'Dracula walking down the street of New York City in the 1920s, black and white photography',
//     'Synthwave aeroplane',
//     'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
//     'A Space Shuttle flying above Cape Town, digital art',
//   ];

export const surpriseMePrompts = [
  'A futuristic computer code transforming into a symphony of music notes.',
  'A sleek software development office inside a high-speed Mercedes G 63.',
  'Stock market charts forming the shape of a powerful sports car.',
  'A financial wizard conjuring code while surrounded by stacks of investment books.',
  'A gym workout routine visualized as a dynamic algorithm.',
  'Public speaking podium on the hood of a roaring Mercedes G 63 at a tech conference.',
  'A musical notation made of binary code floating around a stock market bull.',
  'Investing strategies represented as a high-speed race between sports cars.',
  'A powerful computer mouse driving a Mercedes G 63 through a stock market graph.',
  'Music production studio inside the cockpit of a luxurious sports car.',
  'Software development team brainstorming inside a gym, surrounded by dumbbells.',
  'Financial success portrayed through the acceleration of a sports car.',
  'An intense gym session depicted as a fast-paced computer programming session.',
  'Stock market trends displayed in the rhythm of a musical composition.',
  'A Mercedes G 63 integrated with cutting-edge computer hardware for trading.',
  'A software developer coding while listening to a symphony of financial news.',
  'Investing graphs forming the shape of a powerful engine in a sports car.',
  'A gym filled with finance professionals discussing market trends between sets.',
  'A futuristic stock market dashboard projected on the windshield of a Mercedes G 63.',
  'Musical notes emanating from the exhaust of a high-performance sports car.',
  'Public speaking skills honed through the precision of computer programming.',
  'A gym floor transformed into a stock market trading arena.',
  'Binary code running along the curves of a Mercedes G 63.',
  'Financial success illustrated through the beats of a workout playlist.',
  'Software code intertwined with the design lines of a luxury sports car.',
  'Investment portfolio presented as a playlist of dynamic workout tunes.',
  'A Mercedes G 63 cruising through the lanes of a stock market chart.',
  'A music producer creating beats inspired by the rhythm of financial markets.',
  'Coding algorithms designed with the elegance of a sports car\'s aerodynamics.',
  'A gym session visualized as a live stock market trading floor.',
  'A financial analyst delivering a powerful speech from the driver\'s seat of a Mercedes G 63.',
  'Musical instruments morphing into charts and graphs in a software development studio.',
  'Investing strategies executed with the precision of a gym workout routine.',
  'A powerful sports car designed with the sleekness of software code.',
  'Stock market success celebrated with the revving engine of a sports car.',
  'A Mercedes G 63 conquering a road shaped like a stock market trend line.',
  'Binary code transforming into a melody in the heart of a gym workout.',
  'Public speaking prowess demonstrated while driving a luxurious sports car.',
  'Financial charts displayed on the screens of a futuristic software development lab.',
  'Investment decisions made with the intensity of a high-speed sports car race.',
  'A gym session synchronized with the highs and lows of the stock market.',
  'Musical notes forming the blueprint of a cutting-edge sports car.',
  'A Mercedes G 63 navigating through the peaks and valleys of financial graphs.',
  'Software developers collaborating in a gym, surrounded by the latest trading algorithms.',
  'Investment wisdom shared in a public speaking event held inside a sports car showroom.',
  'A gym transformed into a stock market trading pit, with weights as financial assets.',
  'A financial advisor delivering insights while cruising in a Mercedes G 63.',
  'Binary code evolving into the sleek design of a high-performance sports car.',
  'A workout playlist tailored to the rhythm of the stock market opening bell.',
  'A software development team coding while seated inside a customized Mercedes G 63.',
];
